apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
spec:
  selector:
    app: todoapp
  ports:
    - protocol: TCP
      port: 8000 # Port to expose on the service
      targetPort: 8000 # Port your application is listening on
  type: NodePort
